# <center>Grouping Dataframes</center>

In [1]:
import pandas as pd
import numpy as np

In [38]:
premier_league = pd.read_excel("premier_league_games_full.xlsx")

In [39]:
premier_league.head(10)

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2
5,1734,England Premier League,2008/2009,Everton,Blackburn Rovers,2,3
6,1735,England Premier League,2008/2009,Middlesbrough,Tottenham Hotspur,2,1
7,1736,England Premier League,2008/2009,Bolton Wanderers,Stoke City,3,1
8,1737,England Premier League,2008/2009,Hull City,Fulham,2,1
9,1738,England Premier League,2008/2009,Chelsea,Portsmouth,4,0

In [40]:
premier_league["HomeGoals"].mean()

1.550986842105263

In [41]:
premier_league[["HomeGoals","AwayGoals"]].mean().round(2)

HomeGoals    1.55
AwayGoals    1.16
dtype: float64

In [42]:
premier_league.loc[:,["HomeGoals","AwayGoals"]].mean()

HomeGoals    1.550987
AwayGoals    1.159539
dtype: float64

In [43]:
premier_league["league_name"].unique()

array(['England Premier League'], dtype=object)

In [44]:
premier_league.loc[:,["HomeGoals","AwayGoals"]].std()

HomeGoals    1.311615
AwayGoals    1.144629
dtype: float64

### Grouping Dataframe allow you to aggregate the data at a different level

In [24]:
retail = pd.read_csv("retail_2016_2017.csv")

In [25]:
retail

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

### To group data use the .groupby() method and specify a column to group by

In [30]:
retail.groupby("family")["sales"].mean().round(2).head()

family
AUTOMOTIVE       7.07
BABY CARE        0.25
BEAUTY           5.20
BEVERAGES     3306.44
BOOKS            0.20
Name: sales, dtype: float64

In [33]:
#using double bracket creates a dataframe
retail_family = retail.groupby("family")[["sales"]].mean().round(2)

In [35]:
retail_family.head()

              sales
family
AUTOMOTIVE     7.07
BABY CARE      0.25
BEAUTY         5.20
BEVERAGES   3306.44
BOOKS          0.20

In [46]:
premier_league.groupby("HomeTeam")[["HomeGoals"]].mean().head()

                  HomeGoals
HomeTeam
Arsenal            2.013158
Aston Villa        1.177632
Birmingham City    1.000000
Blackburn Rovers   1.289474
Blackpool          1.578947

In [48]:
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [52]:
premier_league.groupby("season")["HomeGoals"].mean().sort_values(ascending=False)

season
2009/2010    1.697368
2010/2011    1.623684
2011/2012    1.589474
2013/2014    1.573684
2012/2013    1.557895
2015/2016    1.492105
2014/2015    1.473684
2008/2009    1.400000
Name: HomeGoals, dtype: float64