# <center>Aggregating Groups</center>

The .agg() method let you perform multiple aggregation on "groupby" object.

In [1]:
import pandas as pd

In [2]:
retail =pd.read_csv("retail_2016_2017.csv")

In [3]:
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [14]:
#.agg() method perform the aggregation on all compatible columns

mini_retail =(retail.groupby(["store_nbr","family"]).
            agg({'sales':['sum',"mean"],'onpromotion':['min','max']}))

#here we perform sum and mean for sales column
mini_retail

                                             sales              onpromotion  \
                                               sum         mean         min
store_nbr family
1         AUTOMOTIVE                  2.524000e+03     4.263514           0
          BABY CARE                   0.000000e+00     0.000000           0
          BEAUTY                      1.776000e+03     3.000000           0
          BEVERAGES                   1.238601e+06  2092.231419           0
          BOOKS                       2.110000e+02     0.356419           0
...                                            ...          ...         ...
54        POULTRY                     3.553737e+04    60.029334           0
          PREPARED FOODS              4.279200e+04    72.283784           0
          PRODUCE                     3.786125e+05   639.548107           0
          SCHOOL AND OFFICE SUPPLIES  9.970000e+02     1.684122           0
          SEAFOOD                     1.082000e+03     1.827703           0


                                     max
store_nbr family
1         AUTOMOTIVE                   1
          BABY CARE                    0
          BEAUTY                       2
          BEVERAGES                   84
          BOOKS                        0
...                                   ..
54        POULTRY                     11
          PREPARED FOODS               7
          PRODUCE                     83
          SCHOOL AND OFFICE SUPPLIES   8
          SEAFOOD                      2

[1782 rows x 4 columns]

### Inorder to avoid multi-index columns you can name the columns upon creation.

In [16]:
retail_small =(retail.groupby(["family","store_nbr"])
                .agg(sales_sum = ("sales","sum"),sales_avg = ("sales","mean")))

In [17]:
#single column index
retail_small

                         sales_sum  sales_avg
family     store_nbr
AUTOMOTIVE 1           2524.000000   4.263514
           2           3918.000000   6.618243
           3           6790.000000  11.469595
           4           2565.000000   4.332770
           5           3667.000000   6.194257
...                            ...        ...
SEAFOOD    50         12773.966999  21.577647
           51         34250.948976  57.856333
           52          1219.475999   2.059926
           53          3745.180001   6.326318
           54          1082.000000   1.827703

[1782 rows x 2 columns]

In [19]:
league = pd.read_excel("premier_league_games_full.xlsx")

In [20]:
league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [24]:
(league.groupby(["season","HomeTeam"],as_index=False)
 .agg({'HomeGoals':['sum','mean'],
       'AwayGoals':['sum','mean']}))

        season              HomeTeam HomeGoals           AwayGoals
                                           sum      mean       sum      mean
0    2008/2009               Arsenal        31  1.631579        16  0.842105
1    2008/2009           Aston Villa        27  1.421053        21  1.105263
2    2008/2009      Blackburn Rovers        22  1.157895        23  1.210526
3    2008/2009      Bolton Wanderers        21  1.105263        21  1.105263
4    2008/2009               Chelsea        33  1.736842        12  0.631579
..         ...                   ...       ...       ...       ...       ...
155  2015/2016          Swansea City        20  1.052632        20  1.052632
156  2015/2016     Tottenham Hotspur        35  1.842105        15  0.789474
157  2015/2016               Watford        20  1.052632        19  1.000000
158  2015/2016  West Bromwich Albion        20  1.052632        26  1.368421
159  2015/2016       West Ham United        34  1.789474        26  1.368421

[160 rows x 6 columns]

In [27]:
(league.groupby(["season","HomeTeam"],as_index=False)
 .agg(homegoal_sum = ('HomeGoals','sum'),
      awaygoal_sum = ('AwayGoals','sum'),homegoal_mean = ('HomeGoals','mean'),
      awaygoal_mean= ('AwayGoals','mean')))

,season,HomeTeam,homegoal_sum,awaygoal_sum,homegoal_mean,awaygoal_mean
0,2008/2009,Arsenal,31,16,1.631579,0.842105
1,2008/2009,Aston Villa,27,21,1.421053,1.105263
2,2008/2009,Blackburn Rovers,22,23,1.157895,1.210526
3,2008/2009,Bolton Wanderers,21,21,1.105263,1.105263
4,2008/2009,Chelsea,33,12,1.736842,0.631579
...,...,...,...,...,...,...
155,2015/2016,Swansea City,20,20,1.052632,1.052632
156,2015/2016,Tottenham Hotspur,35,15,1.842105,0.789474
157,2015/2016,Watford,20,19,1.052632,1.000000
158,2015/2016,West Bromwich Albion,20,26,1.052632,1.368421
159,2015/2016,West Ham United,34,26,1.789474,1.368421